project:
  type: website
  resources:
    - "videos/**"
    - "images/**"

website:
  title: "Education"
  favicon: images/favicon.ico
  repo-url: https://osu-libraries-research-services.github.io/education/
  google-analytics: "G-BJ38N1FLJT"
  page-navigation: true
  page-footer: 
    left: 
      - text: "© 2026 The Ohio State University"
        href: https://library.osu.edu/policies/copyright-information

  navbar:
    search: true
    logo: images/home_standard_icon.png
    logo-href: https://osu-libraries-research-services.github.io/education/
    left:
      - text: "Highlights"
        href: highlights.qmd
      - text: "Our Choking Times"
        href: our_choking_times.qmd
    right:
      - icon: github
        href: https://github.com/OSU-Libraries-Research-Services/data_visualization

  sidebar:
    - title: "Highlights"
      style: "docked"
      background: light
      contents:
        - section: "HISTORY"
          contents:
            - highlights.qmd
        - section: "LETTERS"
          contents:
            - highlights.qmd
            - highlights.qmd
    - title: "Our Choking Times"
      style: "docked"
      background: light
      contents:
        - section: "INTRODUCTION"
          contents:
            - our_choking_times.qmd
        - section: "SECTION 2"
          contents:
            - our_choking_times.qmd
            - our_choking_times.qmd




format:
  html:
    theme: 
      - simplex
      - styles/custom.scss
    include-in-header:
      - styles/osu-fonts.html
    css: styles.css
    toc: true
    link-external-newwindow: true
