project:
  type: website
  resources:
    - "videos/**"
    - "images/**"

website:
  title: "Education"
  favicon: images/favicon.ico
  repo-url: https://osu-libraries-research-services.github.io/education/
  google-analytics: "G-BJ38N1FLJT"
  page-navigation: true
  page-footer: 
    left: 
      - text: "© 2026 The Ohio State University"
        href: https://library.osu.edu/policies/copyright-information

  navbar:
    search: true
    logo: images/home_standard_icon.png
    logo-href: https://osu-libraries-research-services.github.io/education/
    left:
      - text: "Thematic Unit 1"
        href: unit_1.qmd
      - text: "Thematic Unit 2"
        href: unit_2.ipynb
      - text: "Thematic Unit 3"
        href: unit_3.ipynb
    right:
      - icon: github
        href: https://github.com/OSU-Libraries-Research-Services/data_visualization

  sidebar:
    - title: "Unit 1"
      style: "docked"
      background: light
      contents:
        - section: "INTRODUCTION"
          contents:
            - unit_1.qmd
        - section: "TOOLS"
          contents:
            - unit_2.qmd
            - text: "... Excel"
              href: unit_3.qmd
    - title: "Unit 2"
      style: "docked"
      background: light
      contents:
        - section: "INTRODUCTION"
          contents:
            - unit_2.ipynb
        - section: "WEBSITES AND APIS"
          contents:
            - lantern.ipynb
            - animals.ipynb
    - title: "Unit 3"
      style: "docked"
      background: light
      contents:
        -   contents:
            - text: "Introduction"
              href: unit_3.ipynb
        - section: "TABLEAU AND SURVEYS"
          contents:
            - text: "Introduction"
              href: unit_4.qmd



format:
  html:
    theme: 
      - simplex
      - styles/custom.scss
    include-in-header:
      - styles/osu-fonts.html
    css: styles.css
    toc: true
    link-external-newwindow: true
